#!/bin/bash
# Description: Sets the environment for scripts and console users
#

export RAILS_ENV=production
export HOME=${HOME:-/root}
# Force ExecJS to use node
export EXECJS_RUNTIME='Node'
# workaround for virtual memory spike observed with RHEL6
export MALLOC_ARENA_MAX=1
# Location of certificates and provider keys
export KEY_ROOT=/var/www/miq/vmdb/certs

evm_optional_files="appliance container"
for file in $evm_optional_files; do [[ -s /etc/default/evm_$file ]] && source /etc/default/evm_$file; done

evm_required_files="ruby bundler postgres production"
for file in $evm_required_files; do source /etc/default/evm_$file; done

# Force locale
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

[[ ":$PATH:" == *":/usr/local/bin:"* ]] || PATH="/usr/local/bin:${PATH}"
