#!/bin/bash

export BUNDLE_WITHOUT=test:development
export BUNDLE_GEMFILE=/var/www/miq/vmdb/Gemfile

# This is an environment variable we set in one place in the event
# we want to use --local, --deployment, etc.
export BUNDLE_CLI_OPTIONS=""
